language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install cython python-numpy

install:
  - pip install -e .

script:
  - python -m unittest discover mcd
  - python bin/test_cli.py
